### ISSUE TITLE
sml2mqtt does not reconnect to mqtt broker upon los of connection

### ISSUE THREAD

**Issue by baiti** [spacemanspiff2007/sml2mqtt#20]
As it seems, and by observation, if I shutdown my remote moquitto for maintenance, even if it is just an instant `service mosquitto restart`, sml2mqtt loses its connection and never opens it again. To be on the safe side I typically reboot the raspi that runs sml2mqtt in such a situation. It would be much more reliable, however, if sml2mqtt detects the connection loss and performs an automatic reconnect, permanently and periodically, and never gives up on retry. My tasmota based sensors, which also report via MQTT do exactly that, therefore no manual intervention is ever required if one component in the flowgraph goes down for a while and comes back later.

**Comment by spacemanspiff2007** [comment]
Could you post the error message from the log please?

**Comment by baiti** [comment]
Here is the scenario, everything is running since days (or months) I then take mosquitto down via `service mosquitto stop` (mosquitto is running somewhere else, not on the host where sml2mqtt runs`.  When the nex message is due, the log shows:
```
[2023-01-10 11:40:52,940] [sml.mqtt               ] ERROR    | Error while publishing to sml2mqtt/xxxx/energy: [code:4] The client is not currently connected. (MqttCodeError)
[2023-01-10 11:41:07,945] [sml.mqtt               ] ERROR    | Error while publishing to sml2mqtt/xxxx/power: [code:4] The client is not currently connected. (MqttCodeError)
[2023-01-10 11:42:08,942] [sml.mqtt               ] ERROR    | Error while publishing to sml2mqtt/xxxx/power: [code:4] The client is not currently connected. (MqttCodeError)
```
This now goes on forever, even though I did a `service mosquitto start` after I received the second error message listed above.

While I am typing this, I have now received 8 of those messages. `moquitto` is backup and running and `sml2mqtt` just never even tries to reconnect. At least that is how it looks like by interpreting the logs. I'd expect to see an INFO log indicating that it is trying to reconnect, however, not seeing such a log does not necessarily mean that it isn't trying, however, the subsequent ERROR logs more or less confirm that it isn't.

If I now do a `service sml2mqtt stop` followd by `service sml2mqtt start` everything is back to normal of course.

**Comment by spacemanspiff2007** [comment]
Strange - can you set the logging to DEBUG?
I would have expected at least an Error message that the reconnect fails.
Reconnect should begin after 15 secs

**Comment by spacemanspiff2007** [comment]
Could you try 2.0 and see if the issue is still there?

**Comment by baiti** [comment]
> Could you try 2.0 and see if the issue is still there?

ok, will do, however, might take a while to get back with results. Stay tuned.

**Comment by baiti** [comment]
can I use the `config.yml` unchanged?

**Comment by spacemanspiff2007** [comment]
Can't you just buy a second home so you can test this? ;-)

I'll look into it since I'm very surprised that there's a behavior difference.

**Comment by baiti** [comment]
here is my config for reference:
```
logging:
  level: INFO                    # Log level
  file: sml2mqtt.log             # Log file path (absolute or relative to config file)

mqtt:
  connection:
    client id: sml2mqtt
    host: xxxxxxxxxxxxxxx
    port: 1883
    user: 'xxxxxxxx'
    password: 'xxxxxxxxx'
    tls: false
    tls insecure: false

  defaults:
    qos: 0
    retain: false

  last will:
    topic: status

general:
  Wh in kWh: true                 # Automatically convert Wh to kWh
  republish after: 7200           # Republish automatically after this time (if no other every filter is configured)

ports:
- url: /dev/serial0
  timeout: 3


devices:
  # Device configuration by OBIS value 0100000009ff or by url if the device does not report OBIS 0100000009ff
  #11111111111111111111:
  /dev/serial0:

    mqtt:
      topic: xxxxxxx
    
    skip:
      - '010060320101'
      - '0100600100ff'

    values:

      0100100700ff:
        mqtt:
          topic: power
        filters:
          - diff: 300
          - every: 60

      0100010800ff:
        mqtt:
          topic: energy
        filters:
          - diff: 1
          - every: 300

      0100020800ff:
        mqtt:
          topic: grid
        filters:
          - diff: 1
          - every: 300
```

**Comment by spacemanspiff2007** [comment]
Like this 
```yaml
general:
  device id obis: ["0100600100ff"]
```

or this:
```yaml
general:
  device id obis: 
    - "0100600100ff"
```

Whatever you like better.

> Perhaps this is why it failed ? But there must have been a reason why I needed to add that `'0100600100ff'` to the `skip` list

It's automatically added to the ignore list, so you don't have to do that manually any more.
It prevents sml2mqtt from reporting the serial number through mqtt since it's constant and does never change.

**Comment by baiti** [comment]
Previously, as reported, it died on start. Now with the changed config it keeps running, however, with a warning:

```
[2023-03-23 14:15:25,827] [sml                    ] INFO     | Starting V2.0.0
[2023-03-23 14:15:25,854] [sml.serial0.status     ] INFO     | PORT_OPENED
[2023-03-23 14:15:27,062] [sml.serial0            ] WARNING  | No configuration found for 0a0149534b0005020de2
[2023-03-23 14:15:27,063] [sml.serial0.status     ] INFO     | OK
```

**Comment by baiti** [comment]
something is broken. The new version, with the update config, sends MQTT messages at a high frequency (once per second) to the mosquitto:

```
mosquitto_sub -t 'sml2mqtt/#' -v
sml2mqtt/0a0149534b0005020de2/0100010800ff 3067.1661
sml2mqtt/0a0149534b0005020de2/0100100700ff 1155
sml2mqtt/0a0149534b0005020de2/0100010800ff 3067.1664
sml2mqtt/0a0149534b0005020de2/0100100700ff 745
sml2mqtt/0a0149534b0005020de2/0100010800ff 3067.1665
sml2mqtt/0a0149534b0005020de2/0100100700ff 625
sml2mqtt/0a0149534b0005020de2/0100010800ff 3067.1668
sml2mqtt/0a0149534b0005020de2/0100100700ff 728
sml2mqtt/0a0149534b0005020de2/0100010800ff 3067.1669
sml2mqtt/0a0149534b0005020de2/0100100700ff 81
```

The old version behaved like this, and honoured the time intervals I have in the config:

```
mosquitto_sub -t 'sml2mqtt/#' -v
sml2mqtt/xxx/power 1130
sml2mqtt/xxx/power 730
```

where `xxx` are mnemonic topic fields and not hex values. It seems like my `config.yml` isn't parsed correctly anymore. The only change in `config.yml` is that device id under `generic` as you have outlined it in your first post on the subject:

```
general:
  device id obis: ["0100600100ff"]
```

And I have tried it with that id listed in `skip` and without having it listed in `skip`, no difference.

**Comment by spacemanspiff2007** [comment]
> [2023-03-23 14:15:27,062] [sml.serial0            ] WARNING  | No configuration found for 0a0149534b0005020de2

You have to configure your config as the config that is assigned to `0a0149534b0005020de2`

```
devices:
  # Device configuration by OBIS value 0100000009ff or by url if the device does not report OBIS 0100000009ff
 "0a0149534b0005020de2":
```



> `cd /opt/sml2mqtt` seems wrong as there is no `bin/activate` there.

Thanks for the hint - I'll have to fix the docs!

**Comment by baiti** [comment]
Unfortunately I am not a yaml expert. I tried:

```
devices:
  "0a0149534b0005020de2"
```

and:
```
devices:
  "0a0149534b0005020de2":

and got:

```
 venv/bin/sml2mqtt --config config.yml -a
1 validation error for Settings
devices -> 0a0149534b0005020de2
  none is not an allowed value (type=type_error.none.not_allowed)
```

```

**Comment by spacemanspiff2007** [comment]
```yaml

devices:
  # Device configuration by OBIS value 0100000009ff or by url if the device does not report OBIS 0100000009ff
  # instead of /dev/serial0:
  "0a0149534b0005020de2":

    mqtt:
      topic: xxxxxxx
```
