### ISSUE TITLE
Input data from URL instead of serial device

### ISSUE THREAD

**Issue by the78mole** [spacemanspiff2007/sml2mqtt#30]
Hi Spaceman,

I have a little feature request:

Since [Tibber](https://tibber.com/de) is is more and more common, blocks the IR port of your meter, but a hacked tibber bridge provides the SML data as a whole on a simple URL. It would be awesome, if the config would allow to provide an HTTP endpoint address as the data source for the SML data. 

It would need the following configuration:
- URL: http://tibber-bridge/data.json?node_id=1
- username (default: admin) 
- password (printed on the bridge socket)
- optional: request interval

The procedure to hack your bridge is described in the [openWB community forums](https://openwb.de/forum/viewtopic.php?t=5842&start=60) or on [Wyraz blog](https://blog.wyraz.de/allgemein/a-brief-analysis-of-the-tibber-pulse-bridge/).

Regards,
Daniel

**Comment by spacemanspiff2007** [comment]
Could you provide the http calls and an example response?

**Comment by the78mole** [comment]
the call is just a GET (you can do with a browser, when you have a hacked Tibber Bridge) and the response is a raw binary SML message. I removed the sensitive information from the hex output:

```
the78mole@linux:~/GIT/pysmlparser$ curl -s -u admin:<PASSWORD> http://tibber_bridge/data.json?node_id=1 | xxd -g 1
00000000: 1b 1b 1b 1b 01 01 01 01 76 05 07 3a a7 4e 62 00  ........v..:.Nb.
00000010: 62 00 72 63 01 01 76 01 01 05 02 68 e2 70 0b 09  b.rc..v....h.p..
00000020: 01 49 53 4b .. .. .. .. .. .. .. .. .. .. .. ..  .ISK....&..c...v
00000030: .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..  ..:.Ob.b.rc..w..
00000040: 09 01 49 53 4b .. .. .. .. .. .. .. .. .. .. ..  ..ISK....&...b..
00000050: .. .. .. .. .. .. .. .. .. .. 77 07 81 .. .. ..  .rb.e....zw.....
00000060: 03 ff 01 01 01 01 .. .. .. .. .. 77 07 01 00 00  .......ISK.w....
00000070: 00 09 ff 01 01 01 01 0b 09 01 49 53 4b .. .. ..  ..........ISK...
00000080: .. .. .. 77 07 01 00 01 08 00 ff 65 00 01 01 82  .&.w.......e....
00000090: 01 62 1e 52 ff 59 00 00 00 00 0b e4 ef 03 01 77  .b.R.Y.........w
000000a0: 07 01 00 01 08 01 ff 01 01 62 1e 52 ff 59 00 00  .........b.R.Y..
000000b0: 00 00 0b e4 ef 03 01 77 07 01 00 01 08 02 ff 01  .......w........
000000c0: 01 62 1e 52 ff 59 00 00 00 00 00 00 00 00 01 77  .b.R.Y.........w
000000d0: 07 01 00 02 08 00 ff 01 01 62 1e 52 ff 59 00 00  .........b.R.Y..
000000e0: 00 00 00 00 01 84 01 77 07 01 00 02 08 01 ff 01  .......w........
000000f0: 01 62 1e 52 ff 59 00 00 00 00 00 00 01 84 01 77  .b.R.Y.........w
00000100: 07 01 00 02 08 02 ff 01 01 62 1e 52 ff 59 00 00  .........b.R.Y..
00000110: 00 00 00 00 00 00 01 77 07 01 00 10 07 00 ff 01  .......w........
00000120: 01 62 1b 52 00 55 00 00 02 71 01 77 07 81 81 c7  .b.R.U...q.w....
00000130: 82 05 ff 01 01 01 01 83 02 .. .. .. .. .. .. ..   ..........)....;
00000140: .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..   ...l...K..<...#.
00000150: .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..   .u.m...R..)..`..
00000160: .. .. .. .. .. .. .. .. .. 01 01 01 63 b3 8a 00  k?4..,......c...
00000170: 76 05 07 3a a7 50 62 00 62 00 72 63 02 01 71 01  v..:.Pb.b.rc..q.
00000180: 63 76 1a 00 1b 1b 1b 1b 1a 00 d0 3f              cv.........?
```

I've written a (yet unfinished) blog post about the [Tibber Bridge and getting the SML data](https://the78mole.de/doing-the-undone-decoding-sml-or-hacking-the-tibber-raw-data/).

**Comment by spacemanspiff2007** [comment]
Should be doable. If I hack something together will you test it?

**Comment by the78mole** [comment]
For sure, I'll test it! And I'll extend my blog post 😁

**Comment by christiankratzer** [comment]
Do you know how often you can poll the tibber bridge for new data ?  Does it expose all the samples every second or only the sample it sends off to tibber ?

I would be interested in polling much more frequently than tibber emits a value to their cloud.

**Comment by spacemanspiff2007** [comment]
@the78mole 
I've hacked something together (that is most likely to crash). 
It would be nice to still get early feedback - can you try out the branch:
````
python3 -m pip install git+https://github.com/spacemanspiff2007/sml2mqtt.git@tibbr
````
It's a much larger change than expected

Instead of the com port you can enter `url`, `interval`, `user` and `password`

**Comment by the78mole** [comment]
@christiankratzer : The meter just emits the values every second and this is transferred to Tiber. When you poll the SML from the bridge, it is the most recent dataset from the meter, If you pull more often, you just get duplicates, if there was no new data from the meter.
@spacemanspiff2007 Thanks for implementing this. Unfortunately, I'm completely blocked for the rest of this week by work and private activities. I can test this earliest on sunday.

**Comment by christiankratzer** [comment]
I have received my tibber pulse and have it operational now.  

I have hacked up a python script that polls it every 10s and submits to mqtt.  The meter is sending data to the bridge every second and it can be polled at that rate if desired.

Data can be deduplicated by comparing against the sml transactionId. 

What I have seen though is that the are race conditions that lead to the raw sml sometimes being corrupted. I have wrapped calls to smllib in an exception handler and skip packets that are corrupted.

**Comment by MC68030** [comment]
> @the78mole I've hacked something together (that is most likely to crash). It would be nice to still get early feedback - can you try out the branch:
> 
> ```
> python3 -m pip install git+https://github.com/spacemanspiff2007/sml2mqtt.git@tibbr
> ```
> 
> It's a much larger change than expected
> 
> Instead of the com port you can enter `url`, `interval`, `user` and `password`

Hello,
i tried this specific one, but running gives this issue, from 


[2023-08-12 14:58:41,148] [sml                                          ] INFO     | Starting V2.2
[2023-08-12 14:58:41,149] [asyncio                                   ] DEBUG    | Using selector: EpollSelector
[2023-08-12 14:58:41,149] [sml.192.168.179.29                ] ERROR    | Setup failed
Shutting down ...
[2023-08-12 14:58:41,149] [sml                                          ] INFO     | Shutting down ...

From the conf:
ports:
- url: http://192.168.179.29/nodes/1/data     # Device path
  user: admin
  password: SECRET
  timeout: 3  # Seconds after which a timeout will be detected (default=3)
  interval: 30
devices:   # Device configuration by ID or url
  192.168.179.29:
  
  Any idea?

**Comment by spacemanspiff2007** [comment]
I think you have to start with a fresh setup

**Comment by MC68030** [comment]
Hmm, didn't get it, i started today, and the program created the default config file which i just modified, so it was fresh? If i change one of the keywords, like usWer instead of user, i got the warning about this (wrong) keyword. No change regarding the output if i use 'secret' or 'secret' as coding.
Via curl i'm able to get the raw data from the Tibber pulse.
This

**Comment by spacemanspiff2007** [comment]
I was not aware that you tried a fresh config. from your description it seems like you used an already existing one.
Could you switch the logging to DEBUG and show the output?

**Comment by christiankratzer** [comment]
I have been using a small python script to pull raw data from the tibber bridge and publish to mqtt for a couple of months.  See here for inspriration: https://github.com/christiankratzer/pulse2mqtt

**Comment by MC68030** [comment]
@spacemanspiff2007:
Here we go, i attached the config (secrets cleaned) and the debug output.
From my testing, connection to my mqtt server is working, but there was no outgoing connection to the specified URL for the http SML-device.
[sml2tryconf.txt](https://github.com/spacemanspiff2007/sml2mqtt/files/12329016/sml2tryconf.txt)
[sml2mqtt.log](https://github.com/spacemanspiff2007/sml2mqtt/files/12329017/sml2mqtt.log)

**Comment by spacemanspiff2007** [comment]
There was a small typo which is fixed - could you try again with the updated sources?

**Comment by MC68030** [comment]
Ok, now i'm able to receive OBIS values. But the debug log shows a lot of timeout messages.

[2023-08-14 16:42:10,816] [sml                                                 ] INFO     | Starting V2.2
[2023-08-14 16:42:10,816] [asyncio                                             ] DEBUG    | Using selector: EpollSelector
[2023-08-14 16:42:10,817] [sml.mqtt                                            ] DEBUG    | Connecting to 192.168.179.21:1883
[2023-08-14 16:42:10,819] [sml.mqtt                                            ] DEBUG    | Success!
[2023-08-14 16:42:10,821] [sml.http                                            ] DEBUG    | Requesting data from http://192.168.179.29/data.json?node_id=1
[2023-08-14 16:42:11,821] [sml.192.168.179.29.status                           ] INFO     | MSG_TIMEOUT
[2023-08-14 16:42:11,822] [sml.192.168.179.29                                  ] WARNING  | Timeout
[2023-08-14 16:42:19,908] [sml.192.168.179.29                                  ] DEBUG    | Found obis id 0100000009ff in the sml frame
[2023-08-14 16:42:19,908] [sml.192.168.179.29                                  ] DEBUG    | Configuration found for 090149534b0003d7d03b
[2023-08-14 16:42:19,908] [sml.192.168.179.29                                  ] DEBUG    | Creating default value handler for 0100010800ff
[2023-08-14 16:42:19,908] [sml.192.168.179.29                                  ] DEBUG    | Creating default value handler for 0100010801ff
[2023-08-14 16:42:19,908] [sml.192.168.179.29                                  ] DEBUG    | Creating default value handler for 0100100700ff
[2023-08-14 16:42:19,909] [sml.192.168.179.29                                  ] DEBUG    | Creating default value handler for 0100240700ff
[2023-08-14 16:42:19,909] [sml.192.168.179.29                                  ] DEBUG    | Creating default value handler for 0100380700ff
[2023-08-14 16:42:19,909] [sml.192.168.179.29                                  ] DEBUG    | Creating default value handler for 01004c0700ff
[2023-08-14 16:42:19,909] [sml.192.168.179.29.status                           ] INFO     | OK
[2023-08-14 16:42:20,910] [sml.192.168.179.29.status                           ] INFO     | MSG_TIMEOUT
[2023-08-14 16:42:20,910] [sml.192.168.179.29                                  ] WARNING  | Timeout
[2023-08-14 16:42:29,025] [sml.192.168.179.29.status                           ] INFO     | OK
[2023-08-14 16:42:30,027] [sml.192.168.179.29.status                           ] INFO     | MSG_TIMEOUT
[2023-08-14 16:42:30,027] [sml.192.168.179.29                                  ] WARNING  | Timeout
[2023-08-14 16:42:38,126] [sml.192.168.179.29.status                           ] INFO     | OK
[2023-08-14 16:42:39,127] [sml.192.168.179.29.status                           ] INFO     | MSG_TIMEOUT
[2023-08-14 16:42:39,127] [sml.192.168.179.29                                  ] WARNING  | Timeout
[2023-08-14 16:42:47,232] [sml.192.168.179.29.status                           ] INFO     | OK
[2023-08-14 16:42:48,233] [sml.192.168.179.29.status                           ] INFO     | MSG_TIMEOUT
[2023-08-14 16:42:48,234] [sml.192.168.179.29                                  ] WARNING  | Timeout
[2023-08-14 16:42:56,343] [sml.192.168.179.29.status                           ] INFO     | OK
[2023-08-14 16:42:57,345] [sml.192.168.179.29.status                           ] INFO     | MSG_TIMEOUT
[2023-08-14 16:42:57,345] [sml.192.168.179.29                                  ] WARNING  | Timeout
[2023-08-14 16:43:05,385] [sml.192.168.179.29.status                           ] INFO     | OK
[2023-08-14 16:43:06,387] [sml.192.168.179.29.status                           ] INFO     | MSG_TIMEOUT
[2023-08-14 16:43:06,387] [sml.192.168.179.29                                  ] WARNING  | Timeout
[2023-08-14 16:43:14,464] [sml.192.168.179.29.status                           ] INFO     | OK
...

**Comment by spacemanspiff2007** [comment]
You have to set `timeout` gerater than `interval` in your config. Then the warnings should disappear.
Does everything else work as expected?

**Comment by MC68030** [comment]
Thxs, it's working now and i nice solution, i'm polling two PULSE-devices, and one of the electricity meters needs the workaround for the PV-energy measurement, nice that's included here
Let's see in a couple of days ...

**Comment by spacemanspiff2007** [comment]
Great to hear that. I'll start some more refactoring if you give me the heads up.

**Comment by spacemanspiff2007** [comment]
@MC68030 Does everything work as expected?
@MrFr33man123 Does the branch also work for you?

**Comment by MrFr33man123** [comment]
I will have to setup this branch. Initially i used the docker container. let me try on a lxc container and get back to you. (will update this comment)

**Comment by spacemanspiff2007** [comment]
You can set a MQTT fragment for your device.

```
      OBIS:  # <-- Enter OBIS ID here (case sensetive)
        mqtt:
          topic: OBIS  # <-- This is the sub part of the topic used to build it
```

**Comment by MrFr33man123** [comment]
I cant get the renaming to work.
But values update frequently. Its good. If i can get the renaming to work i would set it up for a long term test.    
```
  values:
      OBIS: 0100010800ff
        # Sub topic how this value is reported.
        mqtt:
          topic: kWh_total_1.8.0
        # Workarounds allow the enabling workarounds (e.g. if the device has strange behaviour)
        # These are the available workarounds
        workarounds:
        - negative on energy meter status: true   # activate this workaround

        # Transformations allow mathematical calculations on the obis value
        # They are applied in order how they are defined
        #transformations:
        #- factor: 3     # multiply with factor
        #- offset: 100   # add offset
        #- round: 2      # round on two digits

        # Filters control how often a value is published over mqtt.
        # If one filter is true the value will be published
        #filters:
        #- diff: 10      # report if value difference is >= 10
        #- perc: 10      # report if percentage change is >= 10%
        #- every: 120    # report at least every 120 secs (overrides the value from general)
      OBIS: 0100020800ff
        mqtt:
          topic: kWh_total_2.8.0
      OBIS: 0100100700ff
        mqtt:
          topic: w_current_power
      OBIS: 0100200700ff
        mqtt:
          topic: v_l1
      OBIS: 0100340700ff
        mqtt:
          topic: v_l2
      OBIS: 0100480700ff
        mqtt:
          topic: v_l3
      OBIS: 01001f0700ff
        mqtt:
          topic: a_l1:
```
I also tried this:

```
0100100700ff:
        mqtt:
          topic: w_current_power
```

can you give an example mqtt rename config?

**Comment by christiankratzer** [comment]
I no longer run sml2mqtt but my config used to look like this:
```
logging:
  level: DEBUG
  file: /opt/sml2mqtt/log/sml2mqtt.log
general:
   report device id: true
mqtt:
  connection:
    host: iot.xxxx.xx
    port: 1883
    user: ''
    password: ''
    tls: false
  topic prefix: sml2mqtt
ports:
  - url: /dev/ttyUSB0
    timeout: 3
devices:
  0a014150410100f43f9a:
    skip:
      - "010060320101"
      - "0100600100ff"
      - "0100020800ff"
    mqtt:
      topic: meter/xxxxx/SENSOR
    values:
        0100010800ff:
          mqtt:
            topic: Total_in
          filters:
            - every: 10
            - diff: 1000
        0100100700ff:
          mqtt:
            topic: Power_curr
          filters:
            - every: 10
            - diff: 1000
```
