### ISSUE TITLE
Default behaviour for publishing over MQTT

### ISSUE THREAD

**Issue by baiti** [spacemanspiff2007/sml2mqtt#31]
Recently when expermimenting with the config, I had removed the `diff` filter accidentally and I had assumed that the `every: 30` I had set would result in one packet every 30s delivered to MQTT. To my surprise, I got 1 packet per second! As it seems, without a `diff` filter, packets get emitted "on change". That means, even when the power reading, for instance, changes by 1 Watt, a packet goes out. Is that really a meaningful default behaviour? I am now back to setting: `diff: 10000`. All I want is a periodic sample rate, no exceptions, therefore the large value on diff now.

```
        # Filters control how often a value is published over mqtt.
        # If one filter is true the value will be published
        filters:
        - diff: 10      # report if value difference is >= 10
        - perc: 10      # report if percentage change is >= 10%
        - every: 120    # report at least every 120 secs (overrides the value from general)
```
