### ISSUE TITLE
validation error for Settings

### ISSUE THREAD

**Issue by hello-world-dot-c** [spacemanspiff2007/sml2mqtt#35]
I followed the instructions at https://sml2mqtt.readthedocs.io/en/latest/installation.html for running sml2mqtt on an SBC under Armbian. I created the config file based on the example but when running sml2mqtt with it, I always get

```
(venv) user@mybox:/opt/sml2mqtt/venv$ sml2mqtt --config ../sml2mqtt.conf
1 validation error for Settings
devices -> 11111111111111111111 -> skip -> 0
  str type expected (type=type_error.str)
```

This happens no matter what I put under "devices" and also when I enclose the value with ""s. An excerpt from my config file:

```
# Serial port configurations for the sml readers
ports:
- url: /dev/ttyUSB0
  timeout: 3


devices:
  11111111111111111111:
    mqtt:
      topic: house

    skip:
    - 010060320101

    values:
```

Python version is 3.9.2.
